# Generated by Django 4.0.4 on 2022-05-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MostrarDatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='email',
            field=models.EmailField(default='N/A', max_length=30),
            preserve_default=False,
        ),
    ]
