# Generated by Django 4.0.4 on 2022-05-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MostrarDatos', '0002_personas_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='fechaNacimiento',
            field=models.DateField(blank=True, default='1995-01-30'),
            preserve_default=False,
        ),
    ]
